version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo_db
      - MONGO_PORT=27017
      - MONGO_DB=camp2016
    depends_on:
      - mongo_db