apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # Allow 1 unavailable pod during rollout (at least 2 running pods at all times for replicas: 3)
      maxSurge: 1         # Allow 1 extra pod during rollout (potentially 4 running pods for replicas: 3)
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: tc4088/todo-kube:latest
        ports:
        - name: http-port
          containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
        # # For testing liveness and readiness probes
        # - name: FLASK_FAILURE
        #   value: "True"
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 20 # Wait 20s before first check
          periodSeconds: 10       # Check every 10s
          failureThreshold: 3     # Restart pod if it fails 3 times in a row        
        readinessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 20 # Wait 20s before first check
          periodSeconds: 5        # Check every 5s
          failureThreshold: 3     # Mark pod as unhealthy (not ready) if it fails 3 times

# # Part 5: Replication controller (redundant)
# ---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: flask-replication-controller
# spec:
#   replicas: 3
#   selector:
#     app: flask-app
#   template:
#     metadata:
#       labels:
#         app: flask-app
#     spec:
#       containers:
#       - name: flask-app
#         image: tc4088/todo-kube:latest
#         ports:
#         - containerPort: 5000
#         env:
#         - name: MONGO_HOST
#           value: "mongo-service"
#         - name: MONGO_PORT
#           value: "27017"