alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by: ["alertname"]
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "slack"
        - matchers:
            - alertname = "LivenessProbeFailures"
          receiver: "slack"
        - matchers:
            - alertname = "ReadinessProbeFailures"
          receiver: "slack"
    receivers:
      - name: "null"
      - name: "slack"
        slack_configs:
          - api_url: "<SLACK_WEBHOOK_URL>"
            channel: "<SLACK_ALERT_CHANNEL>"
            send_resolved: true
            title: "[{{ .Status | toUpper }}] Alert: {{ .CommonLabels.alertname }}"
            text: |
              {{ range .Alerts }}
              *Summary:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              {{ end }}